services:
  webtop:
    image: lscr.io/linuxserver/webtop:ubuntu-mate
    container_name: webtop
    hostname: webtop
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Tokyo
      - LC_ALL=ja_JP.UTF-8
      - USER_NAME=shun
    volumes:
      - ./data:/config
    ports:
      - 3000:3000
      - 3001:3001
    shm_size: "2gb"
    restart: always