services:
  webtop:
    image: lscr.io/linuxserver/webtop:ubuntu-mate
    container_name: webtop
    hostname: webtop
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Tokyo
      - LC_ALL=ja_JP.UTF-8
      - USER_NAME=shun
    volumes:
      - ./data:/config
    shm_size: "2gb"
    restart: always

  app_proxy:
    environment:
      - APP_HOST=webtop
      - APP_PORT=3000