version: "3.7"

services:

  app_proxy:
    environment:
      APP_HOST: shun-webtop_webtop_1
      APP_PORT: 3000

  webtop:
    image: lscr.io/linuxserver/webtop:ubuntu-mate
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ:-UTC}
      - LC_ALL=${LC_ALL:-C.UTF-8}
      - USER_NAME=${USER_NAME:-user}
    volumes:
      - ./data:/config
      - ./init:/config/custom-cont-init.d
    shm_size: "2gb"
    restart: on-failure
